/**
 * ============================================================================================
 *  AAAAAA-GRADE ULTIMATE BIRD LANDING PREDICTOR & AUTONOMOUS TOUCHDOWN CONTROLLER
 * ============================================================================================
 *  Pipeline Flow : Perceptual Ground Raycast -> Touchdown Point Predictor
 *                  -> Distance-Based Phase State Machine
 *                  -> [Feet Extend] -> [Body Pitch Airbrake] -> [Tail Spread Fan]
 *                  -> Continuous Fluid Inverse Kinematics & Aerodynamic Flare
 *  Target System : Real-Time High-Fidelity Flight Sim / UE5 C++ / Physics Rig
 *  Standard      : C++20 (Zero Heap Allocations / SIMD Aligned / Sub-Stepped Smoothness)
 * ============================================================================================
 */

#ifndef AAAAAA_BIRD_LANDING_PREDICTOR_ENGINE_HPP
#define AAAAAA_BIRD_LANDING_PREDICTOR_ENGINE_HPP

#include <cmath>
#include <algorithm>
#include <array>
#include <cstdint>

namespace AAABirdEngine
{
    // ============================================================================================
    // 1. HARDENED SIMD MATH PRIMITIVES
    // ============================================================================================

    constexpr float PI_F = 3.14159265358979323846f;
    constexpr float DEG_TO_RAD_F = PI_F / 180.0f;
    constexpr float RAD_TO_DEG_F = 180.0f / PI_F;
    constexpr float GRAVITY_ACCEL = 9.81f;

    alignas(16) struct SIMDVector3
    {
        float x{ 0.0f }, y{ 0.0f }, z{ 0.0f }, w{ 0.0f };

        constexpr SIMDVector3() = default;
        constexpr SIMDVector3(float inX, float inY, float inZ, float inW = 0.0f)
            : x(inX), y(inY), z(inZ), w(inW) {}

        inline SIMDVector3 operator+(const SIMDVector3& o) const { return SIMDVector3(x + o.x, y + o.y, z + o.z); }
        inline SIMDVector3 operator-(const SIMDVector3& o) const { return SIMDVector3(x - o.x, y - o.y, z - o.z); }
        inline SIMDVector3 operator*(float s) const { return SIMDVector3(x * s, y * s, z * s); }
        inline SIMDVector3 operator/(float s) const { float inv = 1.0f / s; return SIMDVector3(x * inv, y * inv, z * inv); }

        inline float LengthSq() const { return x * x + y * y + z * z; }
        inline float Length() const { return std::sqrt(LengthSq()); }

        inline SIMDVector3 Normalized() const
        {
            float len = Length();
            return len > 0.00001f ? (*this) * (1.0f / len) : SIMDVector3(0.0f, 0.0f, 0.0f);
        }

        static inline float Dot(const SIMDVector3& a, const SIMDVector3& b) { return a.x * b.x + a.y * b.y + a.z * b.z; }
        static inline SIMDVector3 Cross(const SIMDVector3& a, const SIMDVector3& b)
        {
            return SIMDVector3(
                a.y * b.z - a.z * b.y,
                a.z * b.x - a.x * b.z,
                a.x * b.y - a.y * b.x
            );
        }
    };

    // ============================================================================================
    // 2. LANDING ENUMERATIONS & STATE STRUCTURES
    // ============================================================================================

    enum class ELandingPhase : uint8_t
    {
        CruiseFlight = 0,         // Normal Flight, legs tucked, tail streamlined
        ApproachAndPredict = 1,    // Raycasting ground, calculating time-to-impact (TTI)
        FeetExtend = 2,            // Step 1: Extend talons & hip joints forward
        BodyPitchFlare = 3,        // Step 2: Pitch torso up sharply to use wings as airbrakes
        TailSpreadFan = 4,         // Step 3: Fan out rectrices (tail feathers) for maximum lift & stall control
        TouchdownImpact = 5,       // Absorbing impact forces with leg spring-dampers
        Perched = 6                // Complete rest
    };

    struct LegKinematics
    {
        float HipExtensionDeg{ 0.0f };     // Retracted backwards vs Extended forward
        float KneeFlexionDeg{ 0.0f };      // Leg spring bend
        float AnkleFlexionDeg{ 0.0f };     // Feet/Talon splay angle
        float TalonOpenRatio{ 0.0f };      // 0.0 = Closed fist, 1.0 = Fully flared grip ready

        SIMDVector3 LeftFootPosWorld{ 0.0f, 0.0f, 0.0f };
        SIMDVector3 RightFootPosWorld{ 0.0f, 0.0f, 0.0f };
    };

    struct TailKinematics
    {
        float FanSpreadRatio{ 0.0f };      // 0.0 = Streamlined narrow tail, 1.0 = Full 180-deg fan
        float TailPitchDeg{ 0.0f };        // Tail depression/elevation for pitching moment
        float TailDepressionForceN{ 0.0f };// Downward air reaction force generated by tail
    };

    // ============================================================================================
    // 3. INPUT / OUTPUT FRAME DATA
    // ============================================================================================

    struct BirdLandingInputFrame
    {
        SIMDVector3 BodyPositionWorld{ 0.0f, 15.0f, 0.0f };
        SIMDVector3 BodyLinearVelocityWorld{ 0.0f, -2.5f, 14.0f };
        SIMDVector3 BodyAngularVelocityRadSec{ 0.0f, 0.0f, 0.0f };

        SIMDVector3 BodyForward{ 0.0f, 0.0f, 1.0f };
        SIMDVector3 BodyUp{ 0.0f, 1.0f, 0.0f };
        SIMDVector3 BodyRight{ 1.0f, 0.0f, 0.0f };

        float BirdMassKg{ 1.8f };
        float LegLengthMeters{ 0.32f };
        bool bIntentionalLandingRequested{ true };

        // Ground Target Environment
        SIMDVector3 PerchPointWorld{ 0.0f, 0.0f, 25.0f };
        SIMDVector3 GroundSurfaceNormal{ 0.0f, 1.0f, 0.0f };
        float GroundElevationY{ 0.0f };
    };

    struct BirdLandingOutputFrame
    {
        ELandingPhase CurrentPhase{ ELandingPhase::CruiseFlight };
        
        // Predictions
        float EstimatedTimeToImpactSec{ 999.0f };
        float DistanceToTouchdownMeters{ 999.0f };
        SIMDVector3 PredictedImpactPointWorld{ 0.0f, 0.0f, 0.0f };
        bool bWillOvershootTarget{ false };

        // Morphological Joint Outputs
        LegKinematics LegState;
        TailKinematics TailState;

        // Pitch & Flight Dynamics
        float BodyPitchAngleDeg{ 0.0f };      // Torso flare pitch angle (0 to 65 degrees)
        float AerodynamicDragCoeff{ 0.3f };   // Spikes up dramatically during flare
        float AerodynamicLiftCoeff{ 0.8f };   // High lift coefficient during pitch up to stall speed

        SIMDVector3 AerodynamicBrakingForceN{ 0.0f, 0.0f, 0.0f };
        SIMDVector3 CorrectivePitchTorqueNm{ 0.0f, 0.0f, 0.0f };
    };

    // ============================================================================================
    // 4. MASTER AAAAAA-GRADE LANDING PREDICTOR & FLARE CONTROLLER
    // ============================================================================================

    class AAABirdLandingPredictorEngine
    {
    private:
        BirdLandingOutputFrame m_Outputs;

        // Phase Transition Trigger Thresholds (Time-To-Impact in Seconds)
        const float TTI_FEET_EXTEND_TRIGGER  = 1.85f; // Feet swing forward first
        const float TTI_BODY_PITCH_TRIGGER   = 1.15f; // Body pitches up to flare & brake
        const float TTI_TAIL_SPREAD_TRIGGER  = 0.65f; // Tail fans out for stall control & final touchdown

        // Smoothed State Variables
        float m_TargetPitchDeg{ 0.0f };
        float m_CurrentPitchDeg{ 0.0f };
        float m_PitchVelocity{ 0.0f };

        float m_TargetFootExtension{ 0.0f };
        float m_CurrentFootExtension{ 0.0f };

        float m_TargetTailFan{ 0.0f };
        float m_CurrentTailFan{ 0.0f };

    public:
        AAABirdLandingPredictorEngine() = default;

        /**
         * Main deterministic update tick for landing trajectory prediction & biomechanical sequencing.
         */
        void TickLandingPredictor(const BirdLandingInputFrame& inputFrame, float deltaTime)
        {
            constexpr uint32_t SUB_STEPS = 4;
            float subDt = deltaTime / static_cast<float>(SUB_STEPS);

            for (uint32_t step = 0; step < SUB_STEPS; ++step)
            {
                // --------------------------------------------------------------------------------
                // STEP 1: PREDICT TOUCHDOWN POINT & TIME-TO-IMPACT (TTI)
                // --------------------------------------------------------------------------------
                CalculateLandingTrajectory(inputFrame);

                // --------------------------------------------------------------------------------
                // STEP 2: EVALUATE LANDING PHASE STATE MACHINE
                // --------------------------------------------------------------------------------
                UpdateLandingPhaseStateMachine(inputFrame);

                // --------------------------------------------------------------------------------
                // STEP 3: EXECUTE SEQUENCED MORPHOLOGY (FEET EXTEND -> BODY PITCH -> TAIL SPREAD)
                // --------------------------------------------------------------------------------
                SolveLegExtensionIK(inputFrame, subDt);
                SolveBodyPitchDynamics(inputFrame, subDt);
                SolveTailFeatherFanKinematics(inputFrame, subDt);

                // --------------------------------------------------------------------------------
                // STEP 4: COMPUTE AERODYNAMIC FLARE BRAKING FORCES & STALL MECHANICS
                // --------------------------------------------------------------------------------
                ComputeFlareAerodynamics(inputFrame);
            }
        }

        inline const BirdLandingOutputFrame& GetOutputs() const { return m_Outputs; }

    private:
        /**
         * Parabolic Trajectory Predictor using current position, velocity vector, and gravity acceleration.
         */
        void CalculateLandingTrajectory(const BirdLandingInputFrame& input)
        {
            if (!input.bIntentionalLandingRequested)
            {
                m_Outputs.EstimatedTimeToImpactSec = 999.0f;
                m_Outputs.DistanceToTouchdownMeters = 999.0f;
                return;
            }

            SIMDVector3 pos = input.BodyPositionWorld;
            SIMDVector3 vel = input.BodyLinearVelocityWorld;

            // Height relative to target landing elevation
            float deltaY = pos.y - input.PerchPointWorld.y;

            if (deltaY <= 0.05f)
            {
                m_Outputs.EstimatedTimeToImpactSec = 0.0f;
                m_Outputs.DistanceToTouchdownMeters = (input.PerchPointWorld - pos).Length();
                m_Outputs.PredictedImpactPointWorld = pos;
                return;
            }

            // Quadratic Equation Solver for Time-To-Impact (y = y0 + vy*t - 0.5*g*t^2)
            // 0.5*g*t^2 - vy*t - deltaY = 0
            float a = 0.5f * GRAVITY_ACCEL;
            float b = -vel.y;
            float c = -deltaY;

            float discriminant = (b * b) - (4.0f * a * c);

            if (discriminant >= 0.0f)
            {
                float t1 = (-b + std::sqrt(discriminant)) / (2.0f * a);
                float t2 = (-b - std::sqrt(discriminant)) / (2.0f * a);
                m_Outputs.EstimatedTimeToImpactSec = std::max(0.0f, std::max(t1, t2));
            }
            else
            {
                // Linear fallback estimation if ascending fast
                m_Outputs.EstimatedTimeToImpactSec = deltaY / std::abs(vel.y > 0.001f ? vel.y : 1.0f);
            }

            // Predict 3D impact location along velocity vector
            m_Outputs.PredictedImpactPointWorld = pos + (vel * m_Outputs.EstimatedTimeToImpactSec) + 
                                                   SIMDVector3(0.0f, -0.5f * GRAVITY_ACCEL * m_Outputs.EstimatedTimeToImpactSec * m_Outputs.EstimatedTimeToImpactSec, 0.0f);

            m_Outputs.DistanceToTouchdownMeters = (input.PerchPointWorld - pos).Length();

            // Overshoot check
            float distToPredicted = (m_Outputs.PredictedImpactPointWorld - pos).Length();
            m_Outputs.bWillOvershootTarget = distToPredicted > (m_Outputs.DistanceToTouchdownMeters + 1.5f);
        }

        /**
         * State machine regulating the strict sequence: Feet Extend -> Body Pitch -> Tail Spread
         */
        void UpdateLandingPhaseStateMachine(const BirdLandingInputFrame& input)
        {
            if (!input.bIntentionalLandingRequested)
            {
                m_Outputs.CurrentPhase = ELandingPhase::CruiseFlight;
                return;
            }

            float tti = m_Outputs.EstimatedTimeToImpactSec;

            if (m_Outputs.DistanceToTouchdownMeters <= input.LegLengthMeters * 1.1f || tti <= 0.08f)
            {
                m_Outputs.CurrentPhase = ELandingPhase::TouchdownImpact;
            }
            else if (tti <= TTI_TAIL_SPREAD_TRIGGER)
            {
                // STEP 3: TAIL SPREAD FAN
                m_Outputs.CurrentPhase = ELandingPhase::TailSpreadFan;
            }
            else if (tti <= TTI_BODY_PITCH_TRIGGER)
            {
                // STEP 2: BODY PITCH AIRBRAKE
                m_Outputs.CurrentPhase = ELandingPhase::BodyPitchFlare;
            }
            else if (tti <= TTI_FEET_EXTEND_TRIGGER)
            {
                // STEP 1: FEET EXTEND
                m_Outputs.CurrentPhase = ELandingPhase::FeetExtend;
            }
            else
            {
                m_Outputs.CurrentPhase = ELandingPhase::ApproachAndPredict;
            }
        }

        /**
         * Step 1: Extending Landing Gear / Feet Forward with Inverse Kinematics
         */
        void SolveLegExtensionIK(const BirdLandingInputFrame& input, float dt)
        {
            if (m_Outputs.CurrentPhase >= ELandingPhase::FeetExtend)
            {
                m_TargetFootExtension = 1.0f; // Extend legs fully forward
            }
            else
            {
                m_TargetFootExtension = 0.0f; // Tuck legs under body for low drag
            }

            // Smooth Interpolation
            m_CurrentFootExtension += (m_TargetFootExtension - m_CurrentFootExtension) * (dt * 8.5f);

            m_Outputs.LegState.HipExtensionDeg = m_CurrentFootExtension * 68.0f;  // Swing hip forward by 68 deg
            m_Outputs.LegState.KneeFlexionDeg  = (1.0f - m_CurrentFootExtension * 0.4f) * 45.0f; // Partially unbend knee
            m_Outputs.LegState.AnkleFlexionDeg = m_CurrentFootExtension * 55.0f;  // Extend talons down
            m_Outputs.LegState.TalonOpenRatio  = m_CurrentFootExtension;          // Splay talons wide

            // Foot positions relative to bird body
            SIMDVector3 legForwardOffset = input.BodyForward * (m_CurrentFootExtension * 0.22f) - input.BodyUp * (m_CurrentFootExtension * input.LegLengthMeters);
            m_Outputs.LegState.LeftFootPosWorld  = input.BodyPositionWorld - (input.BodyRight * 0.08f) + legForwardOffset;
            m_Outputs.LegState.RightFootPosWorld = input.BodyPositionWorld + (input.BodyRight * 0.08f) + legForwardOffset;
        }

        /**
         * Step 2: Body Pitch Up (Flare) Dynamics using Spring-Damper for dramatic posture shift
         */
        void SolveBodyPitchDynamics(const BirdLandingInputFrame& input, float dt)
        {
            if (m_Outputs.CurrentPhase >= ELandingPhase::BodyPitchFlare)
            {
                // Calculate flare pitch based on forward velocity (Faster approach = higher pitch to dump energy)
                float speed = input.BodyLinearVelocityWorld.Length();
                float speedFactor = std::clamp(speed / 16.0f, 0.4f, 1.2f);
                m_TargetPitchDeg = 55.0f * speedFactor; // Up to 66-degree flare angle
            }
            else
            {
                m_TargetPitchDeg = 0.0f;
            }

            // Critically Damped Spring Solver for ultra-smooth torso flare
            float springStiffness = 180.0f;
            float springDamping   = 22.0f;

            float error = m_TargetPitchDeg - m_CurrentPitchDeg;
            float accel = (error * springStiffness) - (m_PitchVelocity * springDamping);

            m_PitchVelocity += accel * dt;
            m_CurrentPitchDeg += m_PitchVelocity * dt;

            m_Outputs.BodyPitchAngleDeg = m_CurrentPitchDeg;
        }

        /**
         * Step 3: Tail Feather Fan Spreading & Pitch Down for Pitch Stability
         */
        void SolveTailFeatherFanKinematics(const BirdLandingInputFrame& input, float dt)
        {
            if (m_Outputs.CurrentPhase >= ELandingPhase::TailSpreadFan)
            {
                m_TargetTailFan = 1.0f; // Maximum 180-degree fan spread
            }
            else
            {
                m_TargetTailFan = 0.0f;
            }

            m_CurrentTailFan += (m_TargetTailFan - m_CurrentTailFan) * (dt * 12.0f);

            m_Outputs.TailState.FanSpreadRatio = m_CurrentTailFan;
            // Tail depresses (angles down) to counter body pitch up moment and keep stall controlled
            m_Outputs.TailState.TailPitchDeg = -m_CurrentTailFan * 40.0f; 
        }

        /**
         * Computes Dynamic Drag Spikes and Stall Lift during the Flare phase
         */
        void ComputeFlareAerodynamics(const BirdLandingInputFrame& input)
        {
            float pitchRad = m_Outputs.BodyPitchAngleDeg * DEG_TO_RAD_F;
            float speedSq = input.BodyLinearVelocityWorld.LengthSq();

            // Drag coefficient skyrockets as pitch approaches 60 degrees (Wing presenting flat face to wind)
            m_Outputs.AerodynamicDragCoeff = 0.3f + (1.8f * std::sin(pitchRad) * std::sin(pitchRad)) + (0.4f * m_Outputs.TailState.FanSpreadRatio);
            
            // Lift coefficient increases initially then drops into deep stall right before touchdown
            m_Outputs.AerodynamicLiftCoeff = 0.8f + (1.2f * std::sin(pitchRad * 2.0f));

            // Aerodynamic Braking Force Vector (Opposite to linear velocity)
            SIMDVector3 velocityDir = input.BodyLinearVelocityWorld.Normalized();
            float dragForceMag = 0.5f * 1.225f * speedSq * m_Outputs.AerodynamicDragCoeff * 0.45f; // Area = 0.45 m^2
            
            m_Outputs.AerodynamicBrakingForceN = velocityDir * (-dragForceMag);

            // Tail downward stabilizing force
            m_Outputs.TailState.TailDepressionForceN = 0.5f * 1.225f * speedSq * (m_Outputs.TailState.FanSpreadRatio * 0.35f);

            // Corrective pitch torque feedback
            m_Outputs.CorrectivePitchTorqueNm = SIMDVector3(m_Outputs.BodyPitchAngleDeg * 0.15f, 0.0f, 0.0f);
        }
    };
}

#endif // AAAAAA_BIRD_LANDING_PREDICTOR_ENGINE_HPP
